# Generated by Django 5.2.7 on 2025-11-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mhz19', models.FloatField()),
                ('mq2', models.FloatField()),
                ('mq7', models.FloatField()),
                ('mq135', models.FloatField()),
                ('eht22_temp', models.FloatField()),
                ('eht22_humidity', models.FloatField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
