# Generated by Django 5.2.7 on 2025-11-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airqualityrecord',
            old_name='eht22_humidity',
            new_name='dht22_humidity',
        ),
        migrations.RenameField(
            model_name='airqualityrecord',
            old_name='eht22_temp',
            new_name='dht22_temp',
        ),
    ]
